# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

install! 'cocoapods', :deterministic_uuids => false

target 'icu4c-demo (iOS)' do
  use_frameworks!
  pod 'icu4c-iosx'
  #pod 'icu4c-iosx', :git => 'https://github.com/apotocki/icu4c-iosx', :branch => '74'
end

target 'icu4c-demo (macOS)' do
  use_frameworks!
  pod 'icu4c-iosx'
  #pod 'icu4c-iosx', :git => 'https://github.com/apotocki/icu4c-iosx', :branch => '74'
end
